import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Darkest Helper",
  description: "Generated by a dumbass with memory issues",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* Layout UI */}
          <main>
            {children}
          </main>
        </body>
    </html>
  );
}
